export default {
  THEME_CHANGE: 'THEME_CHANGE',//主题更改
  THEME_INIT: 'THEME_INIT',//主题初始化
  SHOW_THEME_VIEW: 'SHOW_THEME_VIEW',//显示主题弹框

  POPULAR_REFRESH: 'POPULAR_REFRESH',//最热数据加载
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',//最热数据加载成功
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',//最热数据加载失败
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',//最热更多数据加载成功
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',//最热更多数据加载失败
  POPULAR_FLUSH_FAVORITE: 'POPULAR_FLUSH_FAVORITE',//最热收藏

  TRENDING_REFRESH: 'TRENDING_REFRESH',//趋势数据加载
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',//趋势数据加载成功
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',//趋势数据加载失败
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',//趋势更多数据加载成功
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',//趋势更多数据加载失败
  TRENDING_FLUSH_FAVORITE: 'TRENDING_FLUSH_FAVORITE',//趋势收藏

  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',//收藏数据加载
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',//收藏数据加载成功
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',//收藏数据加载失败

  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',//加载语言

  SEARCH_LOAD_MORE_SUCCESS: 'SEARCH_LOAD_MORE_SUCCESS',
  SEARCH_LOAD_MORE_FAIL: 'SEARCH_LOAD_MORE_FAIL',
  SEARCH_REFRESH: 'SEARCH_REFRESH',
  SEARCH_CANCEL: 'SEARCH_CANCEL',
  SEARCH_FAIL: 'SEARCH_FAIL',
  SEARCH_REFRESH_SUCCESS: 'SEARCH_REFRESH_SUCCESS',
}
